services:
  backend:
    build:
      context: .
      dockerfile: infrastructure/Dockerfile
    environment:
      - DB_HOST: postgres
      - DB_PORT: 5432
      - DB_USER: app
      - DB_PASSWORD: app
      - DB_NAME: accounting
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
